feat: config ui - add devlake api version tag to sidebar
merico-dev/lake pull request #1769
Opened 2022-04-28 05:07 UTC by e2corporation

### ⚠️ Config-UI / Sidebar / API Version Tag

- [ ] Add Version Tag to sidebar (provided by `/version` endpoint)

### Description
This PR adds a **Version Tag** to Config-UI's Sidebar so that users are aware of the current release version and commit hash being served.

### Does this close any open issues?
#1747

2022-04-28 05:15 UTC, e2corporation commented
Depends on PR #1749

2022-04-29 07:47 UTC, hezyin commented on config-ui/src/components/Sidebar.jsx
> +        <span className='version-tag'>{versionTag || 'dev+unknown'}</span><br />
Same as above

2022-04-29 07:48 UTC, hezyin requested changes
I suggest that we display an empty string as default when we can't get the version info from the API, otherwise this PR looks good.

2022-04-29 07:57 UTC, hezyin approved these changes
LGTM

2022-04-29 08:02 UTC, merged

2022-04-29 14:40 UTC, e2corporation commented
@hezyin This is simply a fallback value to indicate that the `/version` endpoint has a failure and it should alert the developer of a problem, if BE is operating normally only the tag value would show. This can be change to empty string if needed.