Ts migrations
merico-dev/lake pull request #253
Opened 2021-08-19 14:34 UTC by likyh

# Summary

### Key Points

- [ ] This is a breaking change
- [*] New or existing documentation is updated

### Description
We need migrations and entity load for plugin to finish db init.

### Does this close any open issues?
https://github.com/merico-dev/lake/issues/247

### New Behavior
Now Core will read `plugins/migrations/*.ts` or `plugins/**/*.migration.ts` ro run migration when queue start.
Rest will read `rest/migrations/*.ts` ro run migration when rest start.

2021-08-19 14:50 UTC, likyh commented
It's work base on https://github.com/merico-dev/lake/pull/243

2021-08-20 04:55 UTC, narrowizard commented on apps/rest/src/migrations/index.ts
> +if (process.env.NODE_ENV !== 'test') {
If we don't run migration on test env, can we run e2e test properly?  
Just a question, keep free. @likyh

2021-08-20 05:20 UTC, likyh commented on apps/rest/src/migrations/index.ts
> +if (process.env.NODE_ENV !== 'test') {
Because we won't compile in the test, we can use migrations to add directories directly in the test.

2021-08-20 05:32 UTC, narrowizard commented on apps/rest/src/migrations/index.ts
> +if (process.env.NODE_ENV !== 'test') {
we should run migration before e2e test, is that right?  
If so, we may need extra job on github actions `e2e-test`.  
anyway, it doesn't matter now. we can add it when we need.

2021-08-20 06:26 UTC, likyh commented on apps/rest/src/migrations/index.ts
> +if (process.env.NODE_ENV !== 'test') {
I don't know if we need run migrations 😹

2021-08-20 08:59 UTC, narrowizard approved these changes
LGTM

2021-08-21 01:53 UTC, narrowizard commented
Is this PR still good? Seems it need a reabase locally.

2021-08-24 00:30 UTC, jaxzhou commented
i think we should only add migration files in the plugin.  plugins/migrations/*.ts should not be supported. [proposal]

2021-08-24 02:27 UTC, likyh commented
> i think we should only add migration files in the plugin. plugins/migrations/*.ts should not be supported. [proposal]

off course.   `plugins/pluginName/migrations/*.ts` or `plugins/pluginName/**/*.migration.ts`

2021-08-24 02:53 UTC, narrowizard requested changes

2021-08-24 02:53 UTC, narrowizard commented on apps/rest/src/app.module.ts
> +      migrations,
According to the latest pipeline (failed because table is not existed), I think we should 
- add migrations for rest api models in this PR, and also 
- add migration cli at e2e test pipeline. 
- maybe do these jobs for plugin as well.

2021-08-24 08:00 UTC, closed without merging