feat: jenkins plugins
merico-dev/lake pull request #312
Opened 2021-08-31 06:41 UTC by narrowizard

- add jenkins worker
- add jenkins models
- add jenkins storage

# Summary
This PR added jenkins plugin, collecting jenkins jobs and builds data.

### Key Points

- [ ] This is a breaking change
- [x] New or existing documentation is updated

### Does this close any open issues?
#307

2021-08-31 10:13 UTC, narrowizard commented
## Next steps
- using goroutines to fetch jenkins data
- report worker progress 
- create grafana query and dashboard

2021-09-01 05:59 UTC, klesh requested changes
@joncodo @hezyin

2021-09-01 05:59 UTC, klesh commented on plugins/jenkins/jenkins.go
> +func (j Jenkins) Execute(options map[string]interface{}, progress chan<- float32) {
The Jenkins configuration(Host/Username/Password) are read from API request, I think it would be better to read it from Environment Variable via config.go like Jira/Gitlab plugin did.

2021-09-01 06:21 UTC, narrowizard commented on plugins/jenkins/jenkins.go
> +func (j Jenkins) Execute(options map[string]interface{}, progress chan<- float32) {
We should not limit the way to implement plugins, I think both implement is acceptable. I prefer to pass it by options since
- I don't want to read config if not necessary
- Options support dynamically update (we don't need to restart if want to change host/username/password)

2021-09-01 06:48 UTC, likyh commented on plugins/jenkins/jenkins.go
> +func (j Jenkins) Execute(options map[string]interface{}, progress chan<- float32) {
Whatever you decide, it's okay by me. :D

2021-09-01 07:05 UTC, jaxzhou commented on plugins/jenkins/jenkins.go
> +func (j Jenkins) Execute(options map[string]interface{}, progress chan<- float32) {
agree with @narrowizard 
- multi sources supported. 
- no need of restart service to update source info

2021-09-01 07:23 UTC, klesh approved these changes

2021-09-01 07:23 UTC, klesh commented on plugins/jenkins/jenkins.go
> +func (j Jenkins) Execute(options map[string]interface{}, progress chan<- float32) {
I'm merging this PR, @joncodo @hezyin can review this and we can make a decision tomorrow CST

2021-09-01 07:23 UTC, merged